services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labondemand-api
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./backend:/app/backend
      - ./.env:/app/.env  # Monter le fichier .env comme un volume pour qu'il soit accessible
      - ./kubeconfig.yaml:/root/.kube/config:ro # Monter kubeconfig.yaml en lecture seule
    env_file:
      - ./.env  # Utiliser le fichier .env pour injecter les variables d'environnement
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - CLUSTER_EXTERNAL_IP=${CLUSTER_EXTERNAL_IP:-}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - SECURE_COOKIES=${SECURE_COOKIES:-False}
    restart: unless-stopped
    # Si vous souhaitez que l'API démarre uniquement après un autre service 
    # (comme une base de données par exemple), vous pouvez décommenter les lignes suivantes:
    depends_on:
      - db
      - redis
    command: sh -c "sleep 15 && uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    image: nginx:alpine
    container_name: labondemand-frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      # Monter les images partagées utilisées comme favicon/logo
      - ./Diagrammes/Images:/usr/share/nginx/html/Images:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - api
    command: sh -c "sleep 15 && nginx -g 'daemon off;'"

  db:
    image: mariadb:latest
    container_name: labondemand-db
    env_file:
      - ./.env  # Utiliser le fichier .env pour les secrets de la base de données
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - MYSQL_USER=${DB_USER:-labondemand}
      - MYSQL_PASSWORD=${DB_PASSWORD:-labondemand}
      - MYSQL_DATABASE=${DB_NAME:-labondemand}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: labondemand-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

volumes:
  mariadb_data: