version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labondemand-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # Si vous souhaitez que l'API démarre uniquement après un autre service 
    # (comme une base de données par exemple), vous pouvez décommenter les lignes suivantes:
    # depends_on:
    #   - db
  db:
    image: postgres:14
    container_name: labondemand-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=labondemand
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: