version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labondemand-api
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./backend:/app/backend
      - ./.env:/app/.env  # Monter le fichier .env comme un volume pour qu'il soit accessible
    env_file:
      - ./.env  # Utiliser le fichier .env pour injecter les variables d'environnement
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # Si vous souhaitez que l'API démarre uniquement après un autre service 
    # (comme une base de données par exemple), vous pouvez décommenter les lignes suivantes:
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: labondemand-db
    env_file:
      - ./.env  # Utiliser le fichier .env pour les secrets de la base de données
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - MYSQL_USER=${DB_USER:-labondemand}
      - MYSQL_PASSWORD=${DB_PASSWORD:-labondemand}
      - MYSQL_DATABASE=${DB_NAME:-labondemand}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data: